### PR TITLE
Updates for Swift 2

### PR DESCRIPTION
**Pull request by timbroder**

### CODE REVIEW

**Comment by portapipe** [comment]
Good job :+1: 
Have you tested it? I can't right now.

**Comment by broderboy** [comment]
Yeah. I'm using it in an app

Actually, to clarify I've only tested getting from a plist, not setting

**Comment by portapipe** [comment]
Can you test the get too? So I'll merge your push 👍🏻

**Comment by broderboy** [comment]
Hmm. Yeah something is off. The array looks like it has what it needs but it's not writing to the file at

```array.writeToFile(path as String, atomically: false)```

I'll circle back in a few days and take another look. Out of time today

**Comment by timbroder** [comment]
Was able to get back to this. Have added updates per swift2 being final and successfully tested.
Also cleaned up the readme for better syntax highlighting

```swift
        do {
            // test get existing
            print(try plistGet("test1", forPlistNamed: "tests"))
        
            // test set existing
            print(try plistSet("some new valur", forKey: "test1", inPlistNamed: "tests"))
           
            // test adding new
            print(try plistGet("test4", forPlistNamed: "tests"))
            
            // test set existing
            print(try plistSet("some new valu", forKey: "tests4", inPlistNamed: "tests"))
        } catch {
            
        }
```

**Comment by timbroder** [comment]
Thanks for merging!

**Comment by portapipe** [comment]
Thanks for make it compatible with Swift 2 :wink:

**Pull request merged**
